services:
  - type: web
    name: imageto3d-pro
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ui.web.api:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: HITEM3D_ACCESS_TOKEN
        sync: false
      - key: HITEM3D_CLIENT_ID
        sync: false
      - key: HITEM3D_CLIENT_SECRET
        sync: false
